apiVersion: v1
kind: Pod
metadata:
  name: taint
  labels:
    purpose: "taint-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx


