apiVersion: v1
kind: Pod
metadata:
  name: toleration-1
  labels:
    purpose: "tolerations-1-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
  