apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
  app-name: pod-1
spec:
 containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:3.8
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
  app-name: pod-2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:3.8    
